-- Create table for tracking order changes
CREATE TABLE order_changes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  change_type VARCHAR(50) NOT NULL, -- e.g., 'quantity_update', 'status_change', 'item_added', 'item_removed'
  field_name VARCHAR(100), -- e.g., 'quantity', 'status', 'items'
  old_value TEXT,
  new_value TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  item_id BIGINT REFERENCES order_items(id) ON DELETE SET NULL -- NULL if change is not related to specific item
);

-- Add indexes for better query performance
CREATE INDEX order_changes_order_id_idx ON order_changes(order_id);
CREATE INDEX order_changes_user_id_idx ON order_changes(user_id);
CREATE INDEX order_changes_created_at_idx ON order_changes(created_at);

-- Add RLS policies
ALTER TABLE order_changes ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users
CREATE POLICY "Allow read access to authenticated users" ON order_changes
  FOR SELECT TO authenticated
  USING (true);

-- Allow insert access to authenticated users
CREATE POLICY "Allow insert access to authenticated users" ON order_changes
  FOR INSERT TO authenticated
  WITH CHECK (true);

-- Create function to automatically record changes
CREATE OR REPLACE FUNCTION record_order_change()
RETURNS TRIGGER AS $$
DECLARE
  user_id UUID;
BEGIN
  -- Get current user ID from session
  user_id := auth.uid();
  
  IF TG_OP = 'UPDATE' THEN
    -- Record status changes
    IF NEW.status <> OLD.status THEN
      INSERT INTO order_changes (
        order_id,
        user_id,
        change_type,
        field_name,
        old_value,
        new_value
      ) VALUES (
        NEW.id,
        user_id,
        'status_change',
        'status',
        OLD.status,
        NEW.status
      );
    END IF;
    
    -- Add more change tracking as needed
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger for orders table
CREATE TRIGGER track_order_changes
  AFTER UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION record_order_change();

-- Create function to record order item changes
CREATE OR REPLACE FUNCTION record_order_item_change()
RETURNS TRIGGER AS $$
DECLARE
  user_id UUID;
BEGIN
  -- Get current user ID from session
  user_id := auth.uid();
  
  IF TG_OP = 'UPDATE' THEN
    -- Record quantity changes
    IF NEW.quantity <> OLD.quantity THEN
      INSERT INTO order_changes (
        order_id,
        user_id,
        change_type,
        field_name,
        old_value,
        new_value,
        item_id
      ) VALUES (
        NEW.order_id,
        user_id,
        'quantity_update',
        'quantity',
        OLD.quantity::text,
        NEW.quantity::text,
        NEW.id
      );
    END IF;
  ELSIF TG_OP = 'INSERT' THEN
    -- Record new items
    INSERT INTO order_changes (
      order_id,
      user_id,
      change_type,
      field_name,
      old_value,
      new_value,
      item_id
    ) VALUES (
      NEW.order_id,
      user_id,
      'item_added',
      'items',
      NULL,
      json_build_object(
        'product_id', NEW.product_id,
        'quantity', NEW.quantity
      )::text,
      NEW.id
    );
  ELSIF TG_OP = 'DELETE' THEN
    -- Record deleted items
    INSERT INTO order_changes (
      order_id,
      user_id,
      change_type,
      field_name,
      old_value,
      new_value,
      item_id
    ) VALUES (
      OLD.order_id,
      user_id,
      'item_removed',
      'items',
      json_build_object(
        'product_id', OLD.product_id,
        'quantity', OLD.quantity
      )::text,
      NULL,
      OLD.id
    );
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create triggers for order_items table
CREATE TRIGGER track_order_item_changes
  AFTER INSERT OR UPDATE OR DELETE ON order_items
  FOR EACH ROW
  EXECUTE FUNCTION record_order_item_change();
